#===============================================================================
# Conf: conf/tentacle/smoke/1admin-4node-1client-bvt.yaml
# Smoke test cases for
#   - Setup pre-requisites-
#   - Validate package versionss
#===============================================================================

tests:
  - test:
      abort-on-fail: true
      desc: Install software pre-requisites for cluster deployment.
      module: install_prereq.py
      name: setup pre-requisites

  - test:
      abort-on-fail: true
      desc: Validate package versions
      module: test_package_validation.py
      name: Validate package versions
      config:
        server_packages:
          cephadm-ansible: "3.2"
        default_packages:
          chrony: "4.2"
          lvm2: "2.03"
          podman: "4.1"
        dependent_packages:
          ansible-core: "2.12"
          ansible-collection-ansible-posix: "1.2"
          ansible-collection-community-general: "4.0"
        client_packages:
          ceph-common: "19.0"
          ceph-fuse: "19.0"
          cephfs-top: "19.0"
        monitoring_images:
          ose-prometheus-node-exporter: "v4.13.0"
          ose-prometheus: "v4.13.0"
          ose-prometheus-alertmanager: "v4.13.0"
