---
# AWS inventory: instance.create.image-name must be an AMI id (us-east-1).
# Find RHEL 10 AMI: EC2 → AMIs → Public images → search "RHEL-10" or use AWS CLI.
version_id: 10.1
id: rhel
instance:
  create:
    image-name: ami-022be39185ead2baa   # Replace with your RHEL 10 AMI id in us-east-1
    instance_type: t4g.small   # EC2 instance type (e.g. t3.medium, m5.xlarge)

  setup: |
    #cloud-config

    ssh_pwauth: true
    disable_root: false

    groups:
      - cephuser

    users:
      - name: cephuser
        primary-group: cephuser
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
    chpasswd:
      list: |
        root:passwd
        cephuser:pass123
      expire: false

    runcmd:
      - timedatectl set-timezone Etc/UTC
      - hostnamectl set-hostname $(hostname -s)
      - sed -i -e 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
      - systemctl restart sshd
      - update-ca-trust
      - touch /ceph-qa-ready

    final_message: "Ready for ceph qa testing"
