"""
Validate NFS-Ganesha Enable_Metrics survives Ceph upgrade.

Loads the full cephadm default ganesha.conf.j2 template (or an existing config-key
override), injects only ``Enable_Metrics = true``, then reconfig. Never replaces the
template with a minimal NFS_CORE_PARAM-only stub.

Suite config keys:
  operation: before_upgrade | after_upgrade
  nfs_name: cephfs-nfs
  monitoring_port: 9587
  configure_metrics: true  — patch ganesha.conf config-key (before_upgrade only)
  ensure_monitoring_port: true — set orch NFS spec monitoring_port if missing

Validates ganesha.conf Enable_Metrics, the monitoring port, and ``curl <node-ip>:9587/metrics``
on NFS nodes that host a running ``nfs.<name>`` daemon (from ``ceph orch ps``).
"""

from __future__ import annotations

import json
import re
import shlex
import time

import yaml

from cli.cephadm.cephadm import CephAdm
from cli.exceptions import ConfigError, OperationFailedError
from cli.utilities.utils import get_ip_from_node
from tests.nfs.nfs_operations import verify_nfs_ganesha_service
from utility.log import Log

log = Log(__name__)

CONF_KEY = "mgr/cephadm/services/nfs/ganesha.conf"
DEFAULT_TEMPLATE_PATH = (
    "/usr/share/ceph/mgr/cephadm/templates/services/nfs/ganesha.conf.j2"
)
MOUNTED_TEMPLATE_PATH = "/var/lib/ceph/ganesha.conf"
WORK_TEMPLATE_PATH = "/tmp/ganesha_metrics_upgrade_work.conf.j2"
ENABLE_METRICS_LINE = "    Enable_Metrics = true;"
# cephadm ganesha.conf.j2 is a Jinja template — EXPORT/FSAL are not in the template.
GANESHA_TEMPLATE_MARKERS = ("NFS_CORE_PARAM", "NFSv4")
RE_CEPHADM_GENERATED = re.compile(r"generated by cephadm", re.I)
RE_ENABLE_METRICS_TRUE = re.compile(r"(?im)^\s*Enable_Metrics\s*=\s*true\s*;")
RE_ENABLE_METRICS_LINE = re.compile(r"(?im)^\s*Enable_Metrics\s*=\s*\w+\s*;")
RE_PROMETHEUS_METRICS = re.compile(
    r"(?m)^(?:# HELP |# TYPE |[a-zA-Z_:][a-zA-Z0-9_:]*\s)"
)
METRICS_PATH = "/metrics"
METRICS_CURL_TIMEOUT = 15
METRICS_CURL_RETRIES = 6
METRICS_CURL_RETRY_SECONDS = 5
PORT_CHECK_RETRIES = METRICS_CURL_RETRIES
PORT_CHECK_RETRY_SECONDS = METRICS_CURL_RETRY_SECONDS


def _truthy(value) -> bool:
    return str(value).lower() in ("1", "true", "yes")


def _exit_code(node) -> int:
    return int(getattr(node, "exit_status", 1))


def _run_cephadm_shell(node, command: str, check_ec: bool = True) -> str:
    out, _err = node.exec_command(
        sudo=True,
        cmd="cephadm shell -- ceph %s" % command,
        check_ec=check_ec,
    )
    if check_ec and _exit_code(node) != 0:
        raise OperationFailedError(
            "cephadm shell -- ceph %s failed with exit %s on %s"
            % (command, _exit_code(node), node.hostname)
        )
    return out or ""


def _markers_present(content: str, markers: tuple[str, ...]) -> bool:
    return all(marker in (content or "") for marker in markers)


def _missing_markers(content: str, markers: tuple[str, ...]) -> list[str]:
    return [m for m in markers if m not in (content or "")]


def _template_is_complete(content: str) -> bool:
    return _markers_present(content, GANESHA_TEMPLATE_MARKERS)


def _is_minimal_metrics_stub(content: str) -> bool:
    """Detect the broken stub that replaced the full template (IBMCEPH-17615)."""
    if not content or "NFS_CORE_PARAM" not in content:
        return True
    if RE_CEPHADM_GENERATED.search(content):
        return False
    if re.search(r"(?im)NFS_Port\s*=", content):
        return False
    if re.search(r"(?im)Monitoring_Port\s*=", content):
        return False
    if "NFSv4" in content or "RADOS_KV" in content:
        return False
    return bool(RE_ENABLE_METRICS_TRUE.search(content))


def _validate_rendered_conf(path: str, content: str, hostname: str) -> None:
    if _is_minimal_metrics_stub(content):
        raise OperationFailedError(
            "ganesha.conf at %s on %s looks like a truncated NFS_CORE_PARAM-only "
            "stub; restore the full cephadm template" % (path, hostname)
        )
    if not RE_ENABLE_METRICS_TRUE.search(content):
        raise OperationFailedError(
            "Enable_Metrics = true not found in %s on %s" % (path, hostname)
        )


def _command_stdout(node, cmd: str) -> str:
    """Return remote command stdout; do not rely on exit_status for podman/cat."""
    out, _ = node.exec_command(sudo=True, cmd=cmd, check_ec=False)
    return (out or "").strip()


def _run_shell(node, cmd: str) -> str:
    """Run a command that needs shell features (pipes, redirects)."""
    return _command_stdout(node, "bash -c %s" % shlex.quote(cmd))


def _load_default_ganesha_template(installer_node) -> None:
    installer_node.exec_command(
        sudo=True,
        cmd=(
            "cephadm shell -- cat %s > %s" % (DEFAULT_TEMPLATE_PATH, WORK_TEMPLATE_PATH)
        ),
        check_ec=False,
    )
    if _exit_code(installer_node) != 0:
        raise OperationFailedError(
            "Unable to read default Ganesha template from %s" % DEFAULT_TEMPLATE_PATH
        )
    out, _ = installer_node.exec_command(
        sudo=True,
        cmd="cat %s" % WORK_TEMPLATE_PATH,
        check_ec=False,
    )
    if not _template_is_complete(out):
        missing = _missing_markers(out or "", GANESHA_TEMPLATE_MARKERS)
        raise OperationFailedError(
            "Default Ganesha template at %s is incomplete; missing %s"
            % (DEFAULT_TEMPLATE_PATH, ", ".join(missing))
        )


def _load_ganesha_work_template(installer_node) -> None:
    """Load config-key override when complete, otherwise use cephadm default."""
    _run_cephadm_shell(
        installer_node,
        "config-key get %s > %s" % (CONF_KEY, WORK_TEMPLATE_PATH),
        check_ec=False,
    )
    out, _ = installer_node.exec_command(
        sudo=True,
        cmd="cat %s" % WORK_TEMPLATE_PATH,
        check_ec=False,
    )
    if _exit_code(installer_node) != 0 or not _template_is_complete(out):
        log.warning(
            "Ganesha config-key template missing or truncated (missing %s); "
            "loading cephadm default",
            ", ".join(_missing_markers(out or "", GANESHA_TEMPLATE_MARKERS))
            or "template",
        )
        _load_default_ganesha_template(installer_node)

    out, _ = installer_node.exec_command(
        sudo=True,
        cmd="cat %s" % WORK_TEMPLATE_PATH,
        check_ec=False,
    )
    if _exit_code(installer_node) != 0 or not _template_is_complete(out):
        missing = _missing_markers(out or "", GANESHA_TEMPLATE_MARKERS)
        raise OperationFailedError(
            "Unable to load a complete Ganesha template from config-key or default; "
            "missing %s" % ", ".join(missing)
        )


def _apply_ganesha_work_template(installer_node) -> None:
    installer_node.exec_command(
        sudo=True,
        cmd=(
            "cephadm shell --mount %s:%s -- ceph config-key set %s -i %s"
            % (
                WORK_TEMPLATE_PATH,
                MOUNTED_TEMPLATE_PATH,
                CONF_KEY,
                MOUNTED_TEMPLATE_PATH,
            )
        ),
        check_ec=False,
    )
    if _exit_code(installer_node) != 0:
        raise OperationFailedError("Failed to update %s config-key" % CONF_KEY)


def _ensure_enable_metrics_template(installer_node, nfs_name: str) -> None:
    """Inject only Enable_Metrics into the full Ganesha config-key template."""
    _load_ganesha_work_template(installer_node)
    content = _command_stdout(installer_node, "cat %s" % WORK_TEMPLATE_PATH)
    if RE_ENABLE_METRICS_TRUE.search(content):
        log.info("Enable_Metrics = true already present in Ganesha template work copy")
    elif RE_ENABLE_METRICS_LINE.search(content):
        installer_node.exec_command(
            sudo=True,
            cmd=(
                "sed -i -E 's/(Enable_Metrics[[:space:]]*=[[:space:]]*)[A-Za-z]+"
                "(\\s*;)/\\1true\\2/' %s"
            )
            % WORK_TEMPLATE_PATH,
            check_ec=False,
        )
        verify = _command_stdout(
            installer_node,
            "grep -E 'Enable_Metrics[[:space:]]*=[[:space:]]*true' %s"
            % WORK_TEMPLATE_PATH,
        )
        if not verify:
            raise OperationFailedError(
                "Failed to set Enable_Metrics = true in Ganesha template"
            )
    else:
        installer_node.exec_command(
            sudo=True,
            cmd=(
                "grep -q 'NFS_CORE_PARAM {' %s || "
                "{ echo 'NFS_CORE_PARAM block missing from Ganesha template' >&2; exit 1; }"
            )
            % WORK_TEMPLATE_PATH,
            check_ec=False,
        )
        if _exit_code(installer_node) != 0:
            raise OperationFailedError(
                "NFS_CORE_PARAM block missing from Ganesha template"
            )
        installer_node.exec_command(
            sudo=True,
            cmd="sed -i '/NFS_CORE_PARAM {/a\\%s' %s"
            % (ENABLE_METRICS_LINE, WORK_TEMPLATE_PATH),
            check_ec=False,
        )
        verify = _command_stdout(
            installer_node,
            "grep -E 'Enable_Metrics[[:space:]]*=[[:space:]]*true' %s"
            % WORK_TEMPLATE_PATH,
        )
        if not verify:
            raise OperationFailedError(
                "Failed to inject Enable_Metrics into Ganesha template"
            )

    _apply_ganesha_work_template(installer_node)
    _run_cephadm_shell(installer_node, "orch reconfig nfs.%s" % nfs_name)
    verify_nfs_ganesha_service(node=installer_node, timeout=300)


def _nfs_service_name(nfs_name: str) -> str:
    return "nfs.%s" % nfs_name


def _get_nfs_daemons(installer_node, nfs_name: str) -> list[dict]:
    raw = CephAdm(installer_node).ceph.orch.ps(
        service_name=_nfs_service_name(nfs_name),
        format="json",
    )
    if isinstance(raw, tuple):
        raw = raw[0]
    if not raw:
        return []
    try:
        daemons = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise OperationFailedError(
            "Unable to parse ceph orch ps JSON for %s: %s" % (nfs_name, exc)
        ) from exc
    return daemons if isinstance(daemons, list) else []


def _wait_for_nfs_daemons(installer_node, nfs_name: str, timeout: int) -> list[dict]:
    """Wait until ceph orch ps lists running nfs daemons (post-upgrade redeploy)."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        daemons = _get_nfs_daemons(installer_node, nfs_name)
        if _running_daemons(daemons):
            return daemons
        log.info(
            "Waiting for running nfs.%s daemons in ceph orch ps",
            nfs_name,
        )
        time.sleep(PORT_CHECK_RETRY_SECONDS)
    daemons = _get_nfs_daemons(installer_node, nfs_name)
    if _running_daemons(daemons):
        return daemons
    raise OperationFailedError(
        "No running nfs.%s daemons found in ceph orch ps after %ss"
        % (nfs_name, timeout)
    )


def _get_nfs_service_apply_spec(installer_node, nfs_name: str) -> dict:
    """Load an orch-apply-safe NFS service spec (no status/events fields)."""
    raw = _run_cephadm_shell(
        installer_node,
        "orch ls --export --service-name %s -f yaml" % _nfs_service_name(nfs_name),
        check_ec=False,
    )
    if _exit_code(installer_node) != 0 or not raw.strip():
        raise OperationFailedError(
            "Could not export orch spec for %s" % _nfs_service_name(nfs_name)
        )
    try:
        docs = [doc for doc in yaml.safe_load_all(raw) if doc]
    except yaml.YAMLError as exc:
        raise OperationFailedError(
            "Unable to parse exported orch YAML for %s: %s"
            % (_nfs_service_name(nfs_name), exc)
        ) from exc
    if not docs:
        raise OperationFailedError(
            "Exported orch spec for %s is empty" % _nfs_service_name(nfs_name)
        )
    doc = docs[0]
    apply_spec = {
        key: doc[key]
        for key in ("service_type", "service_id", "placement", "spec")
        if key in doc
    }
    apply_spec.setdefault("service_type", "nfs")
    apply_spec.setdefault("service_id", nfs_name)
    apply_spec.setdefault("spec", {})
    return apply_spec


def _node_matches_host(node, host_short: str) -> bool:
    node_short = node.hostname.split(".")[0]
    return node_short == host_short or host_short in node.hostname


def _running_daemons(daemons: list[dict]) -> list[dict]:
    running = []
    for daemon in daemons:
        if (daemon.get("status_desc") or "").lower() != "running":
            continue
        if not daemon.get("container_id"):
            continue
        running.append(daemon)
    return running


def _daemon_host_nodes(nfs_nodes, daemons: list[dict]) -> list[tuple]:
    """Map each running nfs daemon to its cluster node object."""
    pairs = []
    for daemon in _running_daemons(daemons):
        host_short = (daemon.get("hostname") or "").split(".")[0]
        node = next(
            (n for n in nfs_nodes if _node_matches_host(n, host_short)),
            None,
        )
        if node:
            pairs.append((node, daemon))
        else:
            log.warning(
                "Running nfs daemon on %s not found among nfs-labeled cluster nodes",
                daemon.get("hostname"),
            )
    return pairs


def _read_ganesha_conf_from_container(
    node, container_id: str
) -> tuple[str, str] | None:
    content = _command_stdout(
        node, "podman exec %s cat /etc/ganesha/ganesha.conf" % container_id
    )
    if content:
        return "podman://%s/etc/ganesha/ganesha.conf" % container_id, content
    return None


def _read_ganesha_conf_from_host_path(node, nfs_name: str) -> tuple[str, str] | None:
    fsids = node.get_dir_list("/var/lib/ceph", sudo=True)
    if not fsids:
        return None
    base = "/var/lib/ceph/%s" % fsids[0]
    for entry in node.get_dir_list(base, sudo=True):
        if nfs_name not in entry:
            continue
        path = "%s/%s/etc/ganesha/ganesha.conf" % (base, entry)
        content = _command_stdout(node, "cat %s" % path)
        if content:
            return path, content
    return None


def _read_rendered_ganesha_conf(node, nfs_name: str, daemon: dict) -> tuple[str, str]:
    """Read live ganesha.conf from the orch ps container; fall back only if needed."""
    container_id = daemon.get("container_id")
    if container_id:
        found = _read_ganesha_conf_from_container(node, container_id)
        if found:
            path, content = found
            _validate_rendered_conf(path, content, node.hostname)
            return path, content

    found = _read_ganesha_conf_from_host_path(node, nfs_name)
    if found:
        path, content = found
        _validate_rendered_conf(path, content, node.hostname)
        return path, content

    out = _command_stdout(
        node,
        'podman ps --filter name=%s --format "{{{{.ID}}}}"' % nfs_name,
    )
    for cid in out.splitlines():
        cid = cid.strip()
        if not cid or cid == container_id:
            continue
        found = _read_ganesha_conf_from_container(node, cid)
        if found:
            path, content = found
            _validate_rendered_conf(path, content, node.hostname)
            return path, content

    raise OperationFailedError(
        "Unable to read ganesha.conf for %s on %s" % (nfs_name, node.hostname)
    )


def _validate_enable_metrics_in_conf(node, nfs_name: str, daemon: dict) -> None:
    path, content = _read_rendered_ganesha_conf(node, nfs_name, daemon)
    log.info(
        "Verified ganesha.conf with Enable_Metrics at %s on %s",
        path,
        node.hostname,
    )


def _service_has_monitoring_port(service_doc: dict | None, port: int) -> bool:
    if not service_doc:
        return False
    spec_port = (service_doc.get("spec") or {}).get("monitoring_port")
    try:
        return int(spec_port) == int(port)
    except (TypeError, ValueError):
        return False


def _ensure_monitoring_port_on_service(
    installer_node, nfs_name: str, monitoring_port: int
) -> None:
    apply_spec = _get_nfs_service_apply_spec(installer_node, nfs_name)
    if _service_has_monitoring_port(apply_spec, monitoring_port):
        log.info(
            "%s already has spec.monitoring_port=%s",
            _nfs_service_name(nfs_name),
            monitoring_port,
        )
        return

    service = _nfs_service_name(nfs_name)
    apply_spec.setdefault("spec", {})
    apply_spec["spec"]["monitoring_port"] = monitoring_port

    remote_spec = "/tmp/cephci_nfs_metrics_monitoring_port.yaml"
    installer_node.exec_command(
        sudo=True,
        cmd="cat > %s <<'EOF'\n%sEOF"
        % (remote_spec, yaml.safe_dump(apply_spec, sort_keys=False)),
        check_ec=False,
    )
    installer_node.exec_command(
        sudo=True,
        cmd=(
            "cephadm shell --mount %s:%s -- ceph orch apply -i %s"
            % (remote_spec, remote_spec, remote_spec)
        ),
        check_ec=False,
    )
    if _exit_code(installer_node) != 0:
        raise OperationFailedError(
            "Failed to apply monitoring_port=%s on %s" % (monitoring_port, service)
        )
    _run_cephadm_shell(installer_node, "orch reconfig %s" % service)
    verify_nfs_ganesha_service(node=installer_node, timeout=300)


def _port_is_listening(node, port: int) -> tuple[bool, str]:
    port_str = str(port)
    checks = [
        ("ss", "ss -ltn | grep '%s'" % port_str),
        ("netstat", "netstat -tln | grep '%s'" % port_str),
    ]
    for attempt in range(1, PORT_CHECK_RETRIES + 1):
        for tool, cmd in checks:
            out = _run_shell(node, cmd)
            if out and port_str in out:
                if attempt > 1:
                    log.info(
                        "Monitoring port %s visible via %s on %s (attempt %s)",
                        port_str,
                        tool,
                        node.hostname,
                        attempt,
                    )
                return True, tool
        if attempt < PORT_CHECK_RETRIES:
            time.sleep(PORT_CHECK_RETRY_SECONDS)
    return False, "ss=closed, netstat=closed"


def _metrics_curl_hosts(node) -> list[str]:
    hosts = []
    for ip in get_ip_from_node(node) or []:
        if ip.startswith("127."):
            continue
        if ip not in hosts:
            hosts.append(ip)
    if "127.0.0.1" not in hosts:
        hosts.append("127.0.0.1")
    return hosts


def _validate_metrics_endpoint(node, port: int) -> None:
    """curl http://<ganesha-node-ip>:<port>/metrics returns Prometheus exposition text."""
    errors = []
    curl_cmd = "curl -sS --max-time %s" % METRICS_CURL_TIMEOUT
    for host in _metrics_curl_hosts(node):
        url = "http://%s:%s%s" % (host, port, METRICS_PATH)
        cmd = "%s %s" % (curl_cmd, shlex.quote(url))
        for attempt in range(1, METRICS_CURL_RETRIES + 1):
            body = _run_shell(node, cmd)
            if body and RE_PROMETHEUS_METRICS.search(body):
                log.info(
                    "Ganesha /metrics endpoint reachable at %s on %s (attempt %s)",
                    url,
                    node.hostname,
                    attempt,
                )
                return
            if attempt < METRICS_CURL_RETRIES:
                time.sleep(METRICS_CURL_RETRY_SECONDS)
        errors.append(
            "%s: unreachable or empty after %s attempts" % (url, METRICS_CURL_RETRIES)
        )

    raise OperationFailedError(
        "Ganesha /metrics not reachable on %s (%s)"
        % (node.hostname, "; ".join(errors) or "no hosts to probe")
    )


def _validate_nfs_daemon_metrics(
    daemon_nodes: list[tuple], nfs_name: str, port: int
) -> None:
    """Validate metrics conf and monitoring port on nfs daemon host nodes."""
    if not daemon_nodes:
        raise OperationFailedError(
            "No running nfs.%s daemons found in ceph orch ps" % nfs_name
        )

    failures = []
    for node, daemon in daemon_nodes:
        try:
            _validate_enable_metrics_in_conf(node, nfs_name, daemon)
            _validate_metrics_endpoint(node, port)
            listening, detail = _port_is_listening(node, port)
            if listening:
                log.info(
                    "Monitoring port %s is listening on %s (%s)",
                    port,
                    node.hostname,
                    detail,
                )
            else:
                log.warning(
                    "ss/netstat did not list port %s on %s (%s) but /metrics is "
                    "reachable; continuing",
                    port,
                    node.hostname,
                    detail,
                )
        except OperationFailedError as exc:
            failures.append("%s: %s" % (node.hostname, exc))

    if failures:
        raise OperationFailedError(
            "NFS Ganesha metrics validation failed: %s" % "; ".join(failures)
        )


def run(ceph_cluster, **kw):
    config = kw.get("config") or {}
    operation = config.get("operation")
    if operation not in ("before_upgrade", "after_upgrade"):
        raise ConfigError("operation must be before_upgrade or after_upgrade")

    nfs_name = config.get("nfs_name", "cephfs-nfs")
    monitoring_port = int(config.get("monitoring_port", 9587))
    nfs_nodes = ceph_cluster.get_nodes("nfs")
    installer = ceph_cluster.get_nodes("installer")[0]

    if not nfs_nodes:
        raise ConfigError("No NFS nodes found in cluster")

    if operation == "before_upgrade":
        if _truthy(config.get("ensure_monitoring_port", "true")):
            _ensure_monitoring_port_on_service(installer, nfs_name, monitoring_port)
        if _truthy(config.get("configure_metrics", "true")):
            _ensure_enable_metrics_template(installer, nfs_name)

    service_wait_timeout = int(config.get("service_wait_timeout", 300))
    verify_nfs_ganesha_service(node=installer, timeout=service_wait_timeout)
    daemons = _wait_for_nfs_daemons(installer, nfs_name, service_wait_timeout)
    daemon_nodes = _daemon_host_nodes(nfs_nodes, daemons)
    _validate_nfs_daemon_metrics(daemon_nodes, nfs_name, monitoring_port)
    log.info(
        "NFS Ganesha metrics validation (%s) passed for nfs.%s on %s daemon "
        "host(s), port %s",
        operation,
        nfs_name,
        len(daemon_nodes),
        monitoring_port,
    )
    return 0
