tests:
   - test:
       name: install ceph pre-requisites
       module: install_prereq.py
       abort-on-fail: true

   - test:
      name: containerized ceph ansible
      polarion-id: CEPH-83571503
      module: test_ansible.py
      config:
        is_mixed_lvm_configs: True
        ansi_config:
            ceph_test: True
            ceph_origin: distro
            ceph_stable_release: nautilus
            ceph_repository: rhcs
            osd_scenario: lvm
            osd_auto_discovery: False
            journal_size: 1024
            ceph_stable: True
            ceph_stable_rh_storage: True
            ceph_docker_image: rhceph/rhceph-3-rhel7
            ceph_docker_image_tag: latest
            containerized_deployment: true
            ceph_docker_registry: registry.access.redhat.com
            copy_admin_key: true
            dashboard_enabled: True
            dashboard_admin_user: admin
            dashboard_admin_password: p@ssw0rd
            grafana_admin_user: admin
            grafana_admin_password: p@ssw0rd
            node_exporter_container_image: registry.redhat.io/openshift4/ose-prometheus-node-exporter:v4.1
            grafana_container_image: registry.redhat.io/rhceph/rhceph-4-dashboard-rhel8:4
            prometheus_container_image: registry.redhat.io/openshift4/ose-prometheus:4.1
            alertmanager_container_image: registry.redhat.io/openshift4/ose-prometheus-alertmanager:4.1
            ceph_conf_overrides:
                global:
                  osd_pool_default_pg_num: 64
                  osd_default_pool_size: 2
                  osd_pool_default_pgp_num: 64
                  mon_max_pg_per_osd: 1024
                mon:
                  mon_allow_pool_delete: true
                client:
                  rgw crypt require ssl: false
                  rgw crypt s3 kms encryption keys: testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo=
                    testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=
            cephfs_pools:
              - name: "cephfs_data"
                pgs: "8"
              - name: "cephfs_metadata"
                pgs: "8"
      desc: osd with collocated journal
      destroy-cluster: False
      abort-on-fail: true

   - test:
      name: librbd workunit
      module: test_workunit.py
      config:
            test_name: rbd/test_librbd_python.sh
            branch: luminous
            role: mon
      desc: Test librbd unit tests
   - test:
      name: check-ceph-health
      module: exec.py
      config:
            cmd: ceph -s
            sudo: True
      desc: Check for ceph health debug info

   - test:
      name: config roll over mon daemon
      polarion-id: CEPH-9581
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node10.*
                  daemon:
                      - mon
      desc: add containerized monitor
   
   - test:
      name: config roll over new osd daemon
      polarion-id: CEPH-9583
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node11.*
                  daemon:
                      - osd
      desc: add new containerized osd node

   - test:
      name: config roll over existing osd daemon
      polarion-id: CEPH-9582
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node11.*
                  daemon:
                      - osd
      desc: add containerized osd to existing node

   - test:
      name: config roll over client daemon
      polarion-id: CEPH-83573550
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node11.*
                  daemon:
                      - client
      desc: add client
   
   - test:
      name: config roll over rgw daemon
      polarion-id: CEPH-83573550
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node14.*
                  daemon:
                      - rgw
      desc: add rgw

   - test:
      name: config roll over mds daemon
      polarion-id: CEPH-83573550
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node15.*
                  daemon:
                      - mds
      desc: add mds

   - test:
      name: config roll over nfs daemon
      polarion-id: CEPH-83573550
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node16.*
                  daemon:
                      - nfs
      desc: add nfs

   - test:
      name: shrink mon
      polarion-id: CEPH-9584
      module: shrink_mon.py
      config:
           mon-to-kill:
            - .*node6.*
      desc: remove containerized monitor


   - test:
      name: shrink osd
      polarion-id: CEPH-9585
      module: shrink_osd.py
      config:
          osd-to-kill:
            - 3
      desc: remove containerized osd


   - test:
      name: ceph ansible purge
      polarion-id: CEPH-83571493
      module: purge_cluster.py
      config:
           ansible-dir: /usr/share/ceph-ansible
           playbook-command: purge-docker-cluster.yml -e ireallymeanit=yes -e remove_packages=yes
      desc: Purge ceph cluster

   - test:
      name: Check for old container directories
      polarion-id: CEPH-83573507
      module: bug_1834974.py
      desc: Check for old container directories
      destroy-cluster: True
