tests:
  -
    test:
      abort-on-fail: true
      config:
        args:
          - ceph
          - fs
          - set
          - cephfs
          - max_mds
          - "2"
        command: shell
      desc: "Add Active Active configuration of MDS for cephfs"
      destroy-cluster: false
      module: test_bootstrap.py
      name: "Add Active Active configuration of MDS"
      polarion-id: CEPH-11344
