# yaml containing the configurations for pools
replicated:
  sample-pool-1:
    pool_type: replicated
    pool_name: re_pool_10
  sample-pool-2:
    pool_type: replicated
    pool_name: re_pool_20
    pg_num: 32
  sample-pool-3:
    pool_type: replicated
    pool_name: re_pool_30
    pg_num: 128
erasure:
  sample-pool-1:
    pool_name: ec_pool_10
    pool_type: erasure
    k: 4
    m: 3
    crush-failure-domain: host
  sample-pool-2:
    pool_name: ec_pool_20
    pool_type: erasure
    k: 4
    m: 2
    crush-failure-domain: host
  sample-pool-3:
    profile_name: ec86_profile
    pool_name: ec86_msr_pool
    pool_type: erasure
    k: 8
    m: 6
    create_rule: false
    crush-osds-per-failure-domain: 4
    crush-num-failure-domains: 4
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-4:
    profile_name: ec86_profile1
    pool_name: ec86_msr_pool1
    pool_type: erasure
    k: 8
    m: 6
    create_rule: false
    crush-osds-per-failure-domain: 4
    crush-num-failure-domains: 4
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-5:
    pool_name: ec_pool_22
    pool_type: erasure
    k: 2
    m: 2
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-6:
    pool_name: ec_pool_22_1
    pool_type: erasure
    k: 2
    m: 2
    crush-failure-domain: host
  sample-pool-7:
    pool_name: ec_pool_52
    pool_type: erasure
    k: 5
    m: 2
    plugin: isa
    enable_fast_ec_features: true
    crush-failure-domain: host
  sample-pool-8:
    pool_name: ec_pool_52_1
    pool_type: erasure
    k: 5
    m: 2
    plugin: isa
    enable_fast_ec_features: true
    crush-failure-domain: host
  sample-pool-9:
    pool_name: ec_pool_62
    pool_type: erasure
    k: 6
    m: 2
    plugin: isa
    enable_fast_ec_features: true
    crush-failure-domain: host
  sample-pool-10:
    pool_name: ec_pool_62_1
    pool_type: erasure
    k: 6
    m: 2
    plugin: isa
    enable_fast_ec_features: true
    crush-failure-domain: host
  sample-pool-11:
    pool_name: ec_pool_22_2
    pool_type: erasure
    k: 2
    m: 2
    crush-failure-domain: host
    enable_fast_ec_features: true
  sample-pool-12:
    profile_name: ec86_profile
    pool_name: ec86_msr_pool_1
    pool_type: erasure
    k: 8
    m: 6
    create_rule: false
    crush-osds-per-failure-domain: 4
    crush-num-failure-domains: 4
    plugin: jerasure
    crush-failure-domain: host
    enable_fast_ec_features: true
