tests:
  - test:
      name: ceph ansible
      module: test_ansible.py
      config:
        ansi_config:
          ceph_test: True
          ceph_origin: distro
          ceph_repository: rhcs
          osd_scenario: lvm
          osd_auto_discovery: False
          journal_size: 1024
          ceph_stable: True
          ceph_stable_rh_storage: True
          fetch_directory: ~/fetch
          copy_admin_key: true
          dashboard_enabled: False
          ceph_conf_overrides:
            global:
              osd_pool_default_pg_num: 64
              osd_default_pool_size: 2
              osd_pool_default_pgp_num: 64
              mon_max_pg_per_osd: 1024
      desc: test cluster setup using ceph-ansible
      destroy-cluster: false
      abort-on-fail: true
