# yaml containing the configurations for pools
replicated:
  sample-pool-1:
    pool_type: replicated
    pool_name: re_pool_10
  sample-pool-2:
    pool_type: replicated
    pool_name: re_pool_20
    pg_num: 32
  sample-pool-3:
    pool_type: replicated
    pool_name: re_pool_30
    pg_num: 128
erasure:
  sample-pool-1:
    pool_name: ec_pool_10
    pool_type: erasure
    k: 4
    m: 3
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-2:
    pool_name: ec_pool_20
    pool_type: erasure
    k: 4
    m: 2
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-3:
    pool_name: ec_pool_30
    pool_type: erasure
    k: 8
    m: 4
    plugin: jerasure
    crush-failure-domain: osd
  sample-pool-4:
    pool_name: ec_pool_22
    pool_type: erasure
    k: 2
    m: 2
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-5:
    pool_name: ec_pool_22_1
    pool_type: erasure
    k: 2
    m: 2
    plugin: jerasure
    crush-failure-domain: host
  sample-pool-6:
    pool_name: ec_pool_22_1
    pool_type: erasure
    k: 2
    m: 2
    plugin: jerasure
    crush-failure-domain: host
