IO_Profiles = {
    "FIO_WRITE_BS_4k_IODepth8_LIBAIO": {
        "test_name": None,
        "ioengine": "libaio",
        "io_type": "write",
        "device_name": None,
        "bs": "4k",
        "iodepth": 8,
        "size": "100%",
        "group_reporting": True,
        "numjobs": 1,
        "fsync": 32,
        "output_format": "json",
    },
    "FIO_READ_BS_4k_IODepth8_LIBAIO": {
        "test_name": None,
        "ioengine": "libaio",
        "io_type": "read",
        "device_name": None,
        "bs": "4k",
        "iodepth": 8,
        "group_reporting": True,
        "numjobs": 1,
        "fsync": 32,
        "output_format": "json",
        "run_time": "no_runtime",
    },
    "FIO_RW_BS_4k_IODepth8_RWRatio70R_LIBAIO": {
        "test_name": None,
        "ioengine": "libaio",
        "io_type": "readwrite",
        "device_name": None,
        "bs": "4k",
        "iodepth": 8,
        "size": "100%",
        "group_reporting": True,
        "numjobs": 1,
        "fsync": 32,
        "rwmixread": 70,
        "output_format": "json",
    },
}
